name: Update Streams
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.9'}
      - name: Run Script
        run: python scripts/check.py
      - name: Commit changes
        run: |
          git config --global user.name 'bot'
          git config --global user.email 'bot@email.com'
          git add streams/
          git commit -m "Update stream links" || echo "No changes"
          git push
          
